# Generated by Django 5.0.4 on 2024-04-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('model', models.CharField(max_length=150, verbose_name='Модель')),
                ('image', models.FileField(upload_to='phone_image', verbose_name='Картинка')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('Som', 'Som'), ('Dollar', 'Dollar'), ('Euro', 'Euro')], max_length=150, verbose_name='Валюта')),
                ('company', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Mi', 'Mi'), ('Honor', 'Honor'), ('Google', 'Google'), ('Microsoft', 'Microsoft'), ('Nokia', 'Nokia')], max_length=150, verbose_name='Компания')),
                ('published', models.DateField(verbose_name='Дата выпуска')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
    ]
