# Generated by Django 5.0.4 on 2024-04-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('phones', '0002_phone_color_phone_description_phone_memory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='image',
        ),
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ManyToManyField(related_name='phone_images', to='images.image', verbose_name='Картинка'),
        ),
    ]
