# Generated by Django 5.0.4 on 2024-04-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_remove_phone_image_phone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='phone',
            name='is_exists',
            field=models.BooleanField(default=True, verbose_name='Есть в наличии'),
        ),
    ]
