# Generated by Django 5.0.4 on 2024-04-23 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phones', '0004_phone_is_active_phone_is_exists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField(auto_created=True, verbose_name='Дата')),
                ('comment', models.CharField(max_length=500, verbose_name='Отзыв')),
                ('rating', models.IntegerField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], verbose_name='Оценка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_reviews', to='phones.phone')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
